create extension if not exists pgcrypto;

create table if not exists public.financing_calculations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id) on delete cascade,
  client_id uuid null references public.clients (id) on delete set null,
  pre_sale_id uuid null references public.pre_sales (id) on delete set null,
  client_name text not null,
  client_cpf text not null,
  client_phone text null,
  financer_name text null,
  specialist_name text null,
  situation text null,
  expires_at date null,
  service_date date null,
  vehicle text null,
  vehicle_year text null,
  observations text null,
  cash_value numeric(14,2) null,
  down_payment numeric(14,2) null,
  financed_value numeric(14,2) null,
  installment_count integer null,
  current_installment_value numeric(14,2) null,
  paid_installments integer null,
  remaining_installments integer null,
  corrected_installment_value numeric(14,2) null,
  current_total_financing numeric(14,2) null,
  corrected_total_financing numeric(14,2) null,
  abusive_interest_per_installment numeric(14,2) null,
  paid_amount_until_now numeric(14,2) null,
  abusive_interest_paid numeric(14,2) null,
  remaining_amount_to_pay numeric(14,2) null,
  real_debt numeric(14,2) null,
  estimated_savings numeric(14,2) null,
  installment_reduction_remaining numeric(14,2) null,
  discount_30_value numeric(14,2) null,
  discount_90_value numeric(14,2) null,
  debt_after_30_discount numeric(14,2) null,
  debt_after_90_discount numeric(14,2) null,
  example_50_discount_15x numeric(14,2) null,
  example_50_discount_10x numeric(14,2) null,
  example_50_discount_5x numeric(14,2) null,
  pdf_storage_path text null,
  pdf_file_name text null,
  status text not null default 'calculado',
  created_by uuid null references public.user_profiles (id) on delete set null,
  updated_by uuid null references public.user_profiles (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz null default timezone('utc', now())
);

alter table public.financing_calculations
  add column if not exists company_id uuid,
  add column if not exists client_id uuid,
  add column if not exists pre_sale_id uuid,
  add column if not exists client_name text,
  add column if not exists client_cpf text,
  add column if not exists client_phone text,
  add column if not exists financer_name text,
  add column if not exists specialist_name text,
  add column if not exists situation text,
  add column if not exists expires_at date,
  add column if not exists service_date date,
  add column if not exists vehicle text,
  add column if not exists vehicle_year text,
  add column if not exists observations text,
  add column if not exists cash_value numeric(14,2),
  add column if not exists down_payment numeric(14,2),
  add column if not exists financed_value numeric(14,2),
  add column if not exists installment_count integer,
  add column if not exists current_installment_value numeric(14,2),
  add column if not exists paid_installments integer,
  add column if not exists remaining_installments integer,
  add column if not exists corrected_installment_value numeric(14,2),
  add column if not exists current_total_financing numeric(14,2),
  add column if not exists corrected_total_financing numeric(14,2),
  add column if not exists abusive_interest_per_installment numeric(14,2),
  add column if not exists paid_amount_until_now numeric(14,2),
  add column if not exists abusive_interest_paid numeric(14,2),
  add column if not exists remaining_amount_to_pay numeric(14,2),
  add column if not exists real_debt numeric(14,2),
  add column if not exists estimated_savings numeric(14,2),
  add column if not exists installment_reduction_remaining numeric(14,2),
  add column if not exists discount_30_value numeric(14,2),
  add column if not exists discount_90_value numeric(14,2),
  add column if not exists debt_after_30_discount numeric(14,2),
  add column if not exists debt_after_90_discount numeric(14,2),
  add column if not exists example_50_discount_15x numeric(14,2),
  add column if not exists example_50_discount_10x numeric(14,2),
  add column if not exists example_50_discount_5x numeric(14,2),
  add column if not exists pdf_storage_path text,
  add column if not exists pdf_file_name text,
  add column if not exists status text default 'calculado',
  add column if not exists created_by uuid,
  add column if not exists updated_by uuid,
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists updated_at timestamptz default timezone('utc', now());

create index if not exists financing_calculations_company_idx
  on public.financing_calculations (company_id, created_at desc);

create index if not exists financing_calculations_client_idx
  on public.financing_calculations (company_id, client_id);

create index if not exists financing_calculations_pre_sale_idx
  on public.financing_calculations (company_id, pre_sale_id);
