export const grsBackupFormat = "grs-crm-backup";
export const backupFormatVersion = 1;
export const backupRetentionDays = 7;

export const backupRestoreOrder = [
  "companies",
  "user_profiles",
  "academy_chapter_progress",
  "academy_exam_attempts",
  "legal_workflow_stages",
  "legal_payment_types",
  "legal_commission_tiers",
  "finance_categories",
  "finance_accounts",
  "finance_transactions",
  "finance_sales",
  "finance_chargebacks",
  "finance_import_batches",
  "finance_import_rows",
  "finance_audit_logs",
  "lead_sources",
  "leads",
  "totalk_integrations",
  "clients",
  "pre_sales",
  "pre_sale_client_snapshot",
  "pre_sale_debt_holders",
  "pre_sale_financial_cases",
  "pre_sale_payments",
  "financing_calculations",
  "document_templates",
  "generated_documents",
  "legal_payments",
  "client_documents",
  "client_timeline_events",
  "client_tracking_updates",
  "email_templates",
  "email_logs",
  "email_integrations",
  "company_audit_logs",
  "legacy_rd_import",
  "rd_crm_activity_import_batches",
  "rd_crm_activity_import",
  "legal_workflow_bulk_moves",
  "legal_workflow_bulk_move_items",
] as const;
